public enum TokenType {
    IDENTIFIER("IDENTIFICADOR"),
    NUMBER("NUMERO"),
    STRING("CADENA"),
    COMENTARIO_DE_LINEA("COMENTARIO_DE_LINEA"),
    COMENTARIO_DE_VARIAS_LINEAS("COMENTARIO_DE_VARIAS_LINEAS"),
    ASSIGN("OPERADOR_ASIGNACION"),
    PALABRA_CLAVE("PALABRA_CLAVE"),
    BOOLEANO("BOOLEANO"),
    NULL("NULO"),
    OPERADOR_ARITMETICO("OPERADOR_ARITMETICO"),
    OPERADOR_LOGICO("OPERADOR_LOGICO"),
    OPERADOR_RELACIONAL("OPERADOR_RELACIONAL"),
    OPERADOR_COMPARACION("OPERADOR_COMPARACION"),
    MINUS("OPERADOR_RESTA"),
    PLUS("OPERADOR_SUMA"),
    MULT("OPERADOR_MULTIPLICAR"),
    DIV("OPERADOR_DIVIDIR"),
    PUNTO_Y_COMA("PUNTO_Y_COMA"),
    PUNTO("PUNTO"),
    COMA("COMA"),
    CORCHETE_ABIERTO("CORCHETE_ABIERTO"),
    CORCHETE_CERRADO("CORCHETE_CERRADO"),
    PARENTESIS_ABIERTO("PARENTESIS_ABIERTO"),
    PARENTESIS_CERRADO("PARENTESIS_CERRADO"),
    LLAVE_ABIERTA("LLAVE_ABIERTA"),
    LLAVE_CERRADA("LLAVE_CERRADA"),
    MODIFICADOR_ACCESO("MODIFICADOR_ACCESO"),
    MODIFICADOR_COMPORTAMIENTO("MODIFICADOR_COMPORTAMIENTO"),
    ESPACIO_EN_BLANCO("ESPACIO_EN_BLANCO"),
    DOS_PUNTOS("DOS_PUNTOS"),
    ARROBA("ARROBA"),
    INTERROGACION("INTERROGACION"),
    ERROR("ERROR_LEXICO"),
    EOF("FIN_DEL_ARCHIVO"), 
    PRINT("PRINT"),
    IMPORT("IMPORT_LIBRERIA");

    private final String Descripcion;

    TokenType(String descripcion) {
        this.Descripcion = descripcion;
    }

    public String getDescripcion() {
        return Descripcion;
    }
}
